

mod_id=colouredstuff
curse_slug=coloured-stuff
curse_id=911266
mod_version=1.3.4
mod_name=colouredstuff
mod_group_id=com.lothrazar.colouredstuff
mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=colouredstuff
modrinth_id=coloured-stuff

flib_version=0.1.0
flib_file=8022223


